/** @format */

export default Data = [
  {
    img: require("../assets/lol.jpg"),
    logo: require("../assets/lollogo.png"),
    tournamentName: "Arena Free",
    date: "Mon, Jun 12, 8:00PM",
    id: "00987",
    price: "$3",
    scoring: "Best 2 Games",
    bracket: "10",
    duration: "4 hours",
    entryFee: "Free",
    timeLeft: " 2d 3h 2m 2s",
    tournamentStatus: "Join Tournament",
  },
  {
    img: require("../assets/dota.jpg"),
    logo: require("../assets/dotalogo.png"),
    tournamentName: "Turbo Free",
    date: "Mon, Jun 13, 9:00PM",
    id: "01026",
    price: "$3",
    scoring: "Best 2 Games",
    bracket: "10",
    duration: "2 hours",
    entryFee: "Free",
    timeLeft: " 1d 3h 2m 2s",
    tournamentStatus: "Join Tournament",
  },
  {
    img: require("../assets/brawl.jpg"),
    logo: require("../assets/brawllogo.png"),
    tournamentName: "Solo Showdown Free",
    date: "Mon, Jun 14, 9:00PM",
    id: "01040",
    price: "$3",
    scoring: "Best 5 Games",
    bracket: "10",
    duration: "30 minutes",
    entryFee: "Free",
    timeLeft: " 2d 3h 2m 2s",
    tournamentStatus: "Join Tournament",
  },
  {
    img: require("../assets/fortnite.jpg"),
    logo: require("../assets/fortnitelogo.png"),
    tournamentName: "Solo Battle Royale Free",
    date: "Friday, Jun 14, 9:00PM",
    id: "01054",
    price: "$3",
    scoring: "Best 5 Games",
    bracket: "10",
    duration: "2 hours",
    entryFee: "Free",
    timeLeft: " 2d 3h 2m 2s",
    tournamentStatus: "Join Tournament",
  },
  {
    img: require("../assets/valorant.jpg"),
    logo: require("../assets/valorantlogo.png"),
    tournamentName: "Spike Rush Free",
    date: "Saturday, Jun 15, 9:00PM",
    id: "01012",
    price: "$3",
    scoring: "Best 2 Games",
    bracket: "10",
    duration: "1 hours",
    entryFee: "Free",
    timeLeft: " 5d 2h 2m 2s",
    tournamentStatus: "Join Tournament",
  },
];
